# Generated by Django 4.0.4 on 2022-04-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=50)),
                ('Time_stamp', models.DateTimeField(max_length=100)),
                ('Temp', models.IntegerField(max_length=20)),
            ],
        ),
    ]
