# Generated by Django 4.0.4 on 2022-04-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='Temp',
            field=models.IntegerField(),
        ),
    ]
