# Generated by Django 4.0.4 on 2022-04-30 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0002_alter_records_temp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
