# Generated by Django 4.0.4 on 2022-06-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0005_remove_record_profile_pic_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Temp',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='AQI',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='Body_Temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='Humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='Temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
