# Generated by Django 4.0.4 on 2022-06-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0007_profile_blood_group_alter_record_aqi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='AQI',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Body_Temperature',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Humidity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Temperature',
            field=models.FloatField(default=0, null=True),
        ),
    ]
