# Generated by Django 4.0.4 on 2022-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashboardApp', '0008_alter_record_aqi_alter_record_body_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
